#ifndef TABXX_TRADE_MESSAGE_CODE_HPP_
#define TABXX_TRADE_MESSAGE_CODE_HPP_

namespace tabxx {

enum class TradeMsgCode {
    PERFORMED = 0,
    ERROR,
    ERROR_NULL,
    ERROR_UNKNOWN_VALUE,
    CONNECTED,
    TRADING_DAY,
    DISCONNECTED,
    AUTHENTICATE,
    LOGIN,
    LOGOUT,
    SETTLEMENT_INFO,
    SETTLEMENT_INFO_CONFIRM,
    TRADING_ACCOUNT,
    ORDER_INSERT_ERROR,
    ORDER_INSERT_RETURN_ERROR,
    ORDER_INSERTED,
    ORDER_TRADED,
    QUERY_ORDER
};

} // namespace tabxx
#endif // TABXX_TRADE_MESSAGE_CODE_HPP_